unixorn/sysadmin-reading-list

README.md
Zed Shaw has a neat Python book for those starting from scratch.
=> adding Python section

README.md
information for Python and extras around it.
Split the section into:
- tutorials
- sysadmin
- deployment utils
=> Added better support for the Python section

README.md
This PR is to help with issue #8. I didn't want to go crazy linking to each of the sections in the official documentation for each service so instead I just put one link to the root of the documentation. There are also links to a few other resources that I've found handy while coming up to speed with Azure.
Full disclosure: I am a Microsoft employee.
=> add section for Azure

README.md
=> Add some culture books.

README.md
I lumped several changes in together.  Let me know if you'd like me to do them one at a time.
=> Adding Systems Perf: Ent Cloud, VSC and Slack

README.md
Add two PowerShell resources I find useful.
=> Add PowerShell resources.

Contributing.md, LICENSE.md, README.md
Add Windows Administration section
=> Add Windows Administration section

README.md
Add
* The Practice of Cloud System Administration
* The Art of Capacity Planning
* The Art of Monitoring
* Web Operations: Keeping the Data on Time
=> Add more books

README.md
GitMagic is a free book of Git.
Thanks.
=> Add free ebook GitMagic

README.md
* Tools section header didn't have appropriate markdown
* Add missing periods at end of entries
=> Minor text cleanups

.travis.yml, README.md
* Add multi-platform subsection to cloud with link to Terraform
* Expanded why to use configuration management
* Moved Windows Administration section, made it clear help is wanted
there
=> Reorganize and phrasing changes

README.md
* Bash bash
* Update Python and Ruby descriptions
=> Bash bash.

README.md
Added some intro-ish-level Perl resources, as per issue #1
=> Add Perl section

README.md
Add a Docker section. This addresses #40. There is room to add more but
this is a good start.
Add a Docker section, with sub-sections for installing Docker and learning Docker.
Fixes #40.
=> Add Docker Section

README.md
This PR adds the Book "20 Python Libraries You Aren't Using (But Should)" to the Python Section.
"20 Python Libraries You Aren't Using (But Should)" is a collection of 20 Hidden Gems, it does not contain overly common Packages like *requests* but rather contains PyPI packages as well as Little-known Standard Library modules that are really Useful but are not in the general Spotlight.
=> adds "20 Python Libraries You Aren't Using (But Should)"

README.md
This PR adds the Book "Automate the Boring Stuff with Python" to the Python Section.
"Automate the Boring Stuff with Python" is a free Book that helps you with automating repetitive and boring Tasks.
It is especially useful for Sysadmins that normally avoid coding because it helps solving real world, day to day Problems, while being written in an introductory way.
=> adds "Automate the Boring Stuff with Python" to the Python Section.

README.md
Didn't notice missing e before merging previous PR
=> Add missing e

README.md
Fleshing out emacs section for #36 
I added several new links with context for getting started with emacs, including references to the built in tutorial, video tutorials, theming information, starter-kits, and some configs from famous emacsen.
Created as per #36.
=> Fleshing out emacs section.

README.md
* Update TOC
* Add link to [Hello DNS](https://github.com/ahupowerdns/hello-dns)
=> Add link to hello dns

README.md
Add a link to Ben Limmer's [Git Skills Talk](https://github.com/blimmer/1up-git-skills-talk)
=> Add blimmer talk

README.md
Add link to the Pure Bash Bible
=> Add link to the Pure Bash Bible

README.md
Update link to powershell books
=> Update link to powershell books

README.md
A lot of people get stuck with terrible equity deals in their early
careers because they didn't know what to ask for, or how to understand
their offer.
The Holloway Guide explains stock options, RSUs, etc in almost painful
detail. Definitely worth a re-read every time you're considering a job
offer.
Add link to [The Holloway Guide to Equity Compensation](https://www.holloway.com/g/equity-compensation)
=> Add a link to the Holloway Guide to Equity Compensation

Contributing.md, LICENSE.md, PULL_REQUEST_TEMPLATE.md, README.md
=> Update pr template

README.md
We all have to negotiate salary.
Add links to an article and podcast about negotiations for engineers.
=> Add salary negotiation article

.travis.yml, README.md
* Add link to [Safe Ways to do Things in Bash](https://github.com/anordal/shellharden/blob/master/how_to_do_things_safely_in_bash.md) article
* Add link to [shellharden](https://github.com/anordal/shellharden) tool
=> Add shellharden, bash safety tips

README.md
Add link to Michael Kehoe's [sre-interview](https://github.com/michael-kehoe/sre-interview) practice questions
=> Add link to https://github.com/michael-kehoe/sre-interview

PULL_REQUEST_TEMPLATE.md, README.md
* Fix entry sorting within sections
* Text tweaks
=> Text cleanups

README.md
=> Add link to zshelldoc

README.md
=> Add GCP section

README.md
LPTHW isn't free, and has really mixed reviews. The google course is free
Removed the LPTHW course and added the Google course
=> Change Python tutorial

.travis.yml, Contributing.md
Clarify that free resources are preferred to paid ones.
=> Note that free resources are preferred to paid

README.md
Thoroughness and completeness for Azure things.
Added the Az PowerShell module which allows you to interface with Azure with native PS cmdlets.
=> Add Az PowerShell Module for Azure

README.md
* A lot of text formatting tweaks
* Some wording tweaks
* Add link to list of free programming books
=> Add free programming books

.circleci/config.yml, .travis.yml, README.md
travis was acquired and they laid off a ton of people, so switching to circle.
Switched to circleci
=> Switch to circleci

README.md
Alice Goldfuss wrote a great article about her path to becoming an SRE.
* Add link to Goldfuss blog post
=> Add Alice Goldfuss' How to Get Into SRE article

README.md
* Add link to awesome-scalability list
=> Add link to awesome-scalability

README.md
Saw a tweet about more good stuff from Alice Goldfuss
=> Add Alice Goldfuss presentation

.github/PULL_REQUEST_TEMPLATE.md, README.md
* Add Dan Luu's article about the Normalization of Deviance
* Update PR template
* Add license to readme
=> Add article and update license

README.md
* Add link to Writing Well article
=> Add link to Writing Well article

README.md
* Add a new Communications section
=> Add communications section

README.md
This PR adds a section for OpenStack.
Fixes #7 
Add a smattering of links to OpenStack-related content, suitable for anyone unfamiliar with the project - regardless of whether they're interested in deploying it or consuming its APIs via someone else's cloud offering.
=> Add a section on OpenStack

README.md
=> #1 - Adding to Perl resources

README.md
* Add link to [awesome-sre](https://github.com/dastergon/awesome-sre)
=> Add link to awesome-sre list

.github/PULL_REQUEST_TEMPLATE.md, README.md
Add link to https://www.netmeister.org/blog/ops-lessons.html
=> Add link to https://www.netmeister.org/blog/ops-lessons.html

README.md
Start adding Kubernetes resources
* Added link to`kubectx`
* Added link to `krew`
* Began Kubernetes section
* TOC update
=> Start adding k8s resources

README.md
Test fails because kitchen.ci domain is not running a webserver
kitchen.ci domain is not running a webserver, delinked
=> kitchen.ci domain is not running a webserver, delink

.circleci/config.yml
Don't like the intermittent test failures
This causes spurious test fails in circleci, whitelisting.
=> kubernetes.io intermittently refuses connections

README.md
Add link to Julia Evans' zines site
=> Add link to Julia Evans' zines site

README.md
Add link to https://github.com/jamiehannaford/what-happens-when-k8s/
=> Add link to https://github.com/jamiehannaford/what-happens-when-k8s/

README.md
=> Fix incorrect possessive

.circleci/config.yml
Fix some false negatives in the travis `awesome_bot` check
* Add a request delay so that github doesn't throttle us when we're probing a bunch of github-hosted links.
* vimeo.com sometimes has 500 issues when we verify links there, ignore them.
=> Update awesome_bot configuration in travis checks

README.md
Worked on the wording and formatting of the `git` commit section, did
some other minor wording and format tweaks since I was editing it
anyway.
=> Minor rewrite of git commit section, wording tweaks

README.md
Add link to https://github.com/donnemartin/system-design-primer
=> Add link to Donne Martin's system-design-primer

README.md
Add links to devops-questions and devops-resources repositories
=> Add devops questions

README.md
* Add Ripienaar's list of free infradev and devops services
=> Add Ripienaar's list of free infradev and devops services

README.md
* Add link to tools.tldr.run
* Update TOC
=> Add security tools

README.md
Add link to [awesome-ssh](https://github.com/moul/awesome-ssh) list
=> Add link to awesome-ssh list

README.md
`awk` is still a very useful tool, add a section about it
=> First pass at adding an `awk` section

.circleci/config.yml, README.md
* Add monitoring section, start with Grafana and Prometheus
* Update broken Powershell Slack link
=> Add a monitoring section

README.md
They've switched to invite mode, so send people to the landing page instead of having to fix this every time the code changes.
Update link for poshcode.org slack
=> Fix broken poshcode slack link

README.md
=> Added Chocolately and OSquery (hacktoberfest)

README.md
=> Added Python 101 --- Introduction to Python book - Hacktoberfest

README.md
I just wanted to make a contribution.
I ran the [Markdownlint plugin for VSCode](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint)and fixed the issues. I didn't make any content changes.
=> Cleaned up Markdown with Markdownlint plugin

README.md
CFEngine, despite it being around for 27 years is still in active development and supports most modern (and many older) systems.  I think it is still worth considering in the right environments.
- [ x] New entry
- [ x] All new and existing tests pass.
- [ x] List entries are sorted alphabetically.
- [ x] Any list entries are one line. This makes it easier to keep the sections sorted. We let the markdown renderer handle line breaks.
- [x ] I confirmed that all the links in my PR are valid.
=> Add cfengine to configuration management

README.md
To spread knowledge on useful site
added commandlinefu site to bash section
- [x ] I assign copyright to the changes in this PR to Joseph Block per the [Attribution-NonCommercial-ShareAlike 4.0 International](#attribution-noncommercial-sharealike-40-international) license.
- [ x] New entry
=> added commandlinefu site to bash section

README.md
Update link to Phil Hagelberg's emacs configuration
=> Update link to Phil Hagelberg's emacs configuration

README.md
* Update minikube tutorial link
=> Update minikube tutorial link

README.md
* Add link to [Bash Guide](https://mywiki.wooledge.org/BashGuide)
=> Add link to the Bash Guide

README.md
=> Add link to nohello.com

README.md
- Add link to The Art of the Command Line
=> Add link to The Art of the Command Line

README.md
Add link to [Regex for Noobs](https://www.janmeppe.com/blog/regex-for-noobs/)
=> Add link to Regex for Noobs post

.github/PULL_REQUEST_TEMPLATE.md, Contributing.md
Update PR template and Contributing.md
=> Update PR template and Contributing.md

README.md
=> Add link to VMWare's kubernetes courses

README.md
Added podcasts & newsletters
- Corecursive
- DevOps'ish
- On the Metal
- Last Week in Kubernetes Development
- Monitoring Weekly
- SRE Weekly
- Last Week in AWS
=> Add more podcasts and newsletters

README.md
- Add link to [An Engineer's guide to Stock Options](https://blog.alexmaccaw.com/an-engineers-guide-to-stock-options/)
=> Add link to Alex MacCaw's post on stock options

README.md
Added a couple of `jq` tutorial links
=> Add json/jq section

README.md
Clean up badges post default branch rename from `master` to `main`.
=> Badge fix - master branch was renamed to main

README.md
Add link to the Python Koans site for learning Python.
=> Add link to Python Koans

README.md
Add link to FSN article on handling the salary expectation question.
=> Add link to Fearless Salary Negotiation

README.md
Add link to Ben Beltzer's stock options article
=> Add link to Ben Beltzer's stock options article

README.md
autoregex.xyz translates regexes to English, and also can accept an English-language description of a regex like "First character A, second character B, up to three B characters, then a C and end of line" and translate that into a valid regular expression.
=> Add autoregex.xyz

.github/PULL_REQUEST_TEMPLATE.md, README.md
=> Add contributor gallery image

README.md
Depends on #150
This repository is copyright 2017-2022 Joseph Block under a [Attribution-NonCommercial-ShareAlike 4.0 International](#attribution-noncommercial-sharealike-40-international) license.
=> readme: Make formatting more consistent

README.md
This repository is copyright 2017-2022 Joseph Block under a [Attribution-NonCommercial-ShareAlike 4.0 International](#attribution-noncommercial-sharealike-40-international) license.
=> Add Windows section and improve existing sections

.github/PULL_REQUEST_TEMPLATE.md, .github/dependabot.yml, .github/workflows/awesomebot.yml, README.md
- Have dependabot keep track of updates to our GitHub actions.
- Copyright updates
=> Add dependabot.yml, update copyright dates

README.md
Add drduh yubiky-guide to SSH Section
Adding this repository because it has great in-depth tutorials on how to use Yubikey's with SSH and GPG.
=> add drduh yubikey-guide to SSH section.

README.md
Add link to Patrick Mackenzie's _Don't Call Yourself A Programmer, And Other Career Advice_ blog post
=> Add _Don't Call Yourself A Programmer, And Other Career Advice_ link

README.md
- Add k3s to Kubernetes utilities
=> Add link to k3s

README.md
https://github.com/Azure/azure-xplat-cli is 404, remove.
=> Remove Azure/azure-xplat-cli

README.md
- Add link to `GNU Coreutils Package Guide`
- Add contributors badge
=> Add contributor badge and link to GNU Coreutils Package Guide

README.md
https://jesswhite.co.uk/blog/practical-dashboards-part1 is 404, remove
=> jesswhite.co.uk is offline

README.md
_Of course_ Microsoft doesn't redirect the old links to new locations.
- Deleted `Azure Code Samples` link because I couldn't find a link to a collection of them, just to individual samples.
=> Update Azure links

.github/workflows/awesomebot.yml
Update awesomebot configuration - 409 is a temporary failure, ignore them.
=> 409 is a temporary failure, ignore them

.github/workflows/awesomebot.yml
Don't want other people's crappy servers causing our link checks to fail.
=> Ignore 500 errors

.github/workflows/awesomebot.yml
=> Ignore 403 and 418 errors
